### ISSUE TITLE
getNumRetriesLastConversion() mentioned (more than once) but does not exist

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#15]
https://github.com/Erriez/ErriezDHT22/blob/c3a7c90930236d4f5c373edbe22afae7f816cbe0/src/ErriezDHT22.cpp#L120

**Comment by Erriez** [comment]
getNumRetriesLastConversion() exists in features/hysteresis branch, but not in master.

**Comment by baskapteijn** [comment]
Jup correct. But in master it is still mentioned in the doxygen of other functions. Thats why i created this ticket. Requires cleanup.

**Comment by Erriez** [comment]
Can you review [this pull request](https://github.com/Erriez/ErriezDHT22/pull/16)?
