### ISSUE TITLE
Resistor not required?

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#2]
See: 

https://raspberrypi.stackexchange.com/questions/12161/do-i-have-to-connect-a-resistor-to-my-dht22-humidity-sensor

Most mention it's required, your text and code doesn't. Can you elaborate in your readme why you don't need it or add that you need it?

**Comment by Erriez** [comment]
Thanks for your feedback. Yes, a 3k3..10k pull-up resistor is required for the AM2302 sensor DAT pin. However:
* A 3k3 resistor is already mounted between the DAT and VCC pins on a DHT22 Senor breakout.
You can see the black SMD resistor on the picture:
[DHT22 breakout PCB](https://raw.githubusercontent.com/Erriez/ErriezDHT22/master/extras/AM2302_DHT22_sensor.png)

* This DHT22 library initializes the IO pin with ```INPUT_PULLUP``` in ```begin()```.
```
// Try to enable internal pin pull-up resistor when available
pinMode(_pin, INPUT_PULLUP);
```

* Some microcontrollers don't have an internal built-in pull-up resistor. Only in this case an external pull-up resistor should be connected between the DAT and VCC pins.

Comments added in commit [#19c15a9cbf](https://github.com/Erriez/ErriezDHT22/commit/19c15a9cbfb846ba92f2cca8f23d75aa3df1a508).

**Comment by baskapteijn** [comment]
Perfect, closing issue.
