### ISSUE TITLE
Overflow protection on millis()

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#4]
See:

https://www.arduino.cc/reference/en/language/functions/time/millis/

This overflow will occur after 50 days. This might lead to reading a sensor value too early when ```_lastMeasurementTimestamp``` ended near unsigned long max.

```
bool DHT22::available()
{
    if ((millis() - _lastMeasurementTimestamp) < 2000) {
        // Interval between sensor reads too short
        return false;
    }

    // Ready to readSensorData humidity and temperature
    return true;
}
```
Not a massive problem but it can probably be easily fixed too.

**Comment by Erriez** [comment]
Overflows with ```millis()``` is a known Arduino limitation. The calculation is used to prevent a continues sensor read stream which increases the internal chip temperature. 

A timer overflow may occur every 50 days, but exactly in the middle of the temperature read. The risk is low and may not hangup reads.

Notice that this is a low-cost sensor which may not be used in safety critical applications as described in the datasheet. I've added design decisions in commit [eaccbf9.](https://github.com/Erriez/ErriezDHT22/commit/eaccbf91f218c5cfd3764329c3b97347409ed738)

**Comment by baskapteijn** [comment]
Not in the middle of a read, it will cause 2 quick reads after another (so for 1 time every 50 days your overheat protector will not work). Not a big problem, just easily fixed if you want to make it perfect :).

But you may close this if you dont want to fix it offcourse.

**Comment by Erriez** [comment]
> for 1 time every 50 days your overheat protector will not work

Worse case you miss only one sample. It continues 2 seconds later which is not an issue.

Consider the increased flash size verses the low risk impact, so won't fix it.
