### ISSUE TITLE
Dont disable interrupts during measurePulseWidth()

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#6]
If the ```noInterrupts``` call disables all interrupts, which i assume, this will skue timing of the whole system.

Its probably better to trigger on the gpio level interrupts, this doesnt require interrupt disables. However, im not sure if all (or any) targets support gpio input level interrupts, so this might not be a valid option.

If not, and there is no alternative, we should close this issue (because its a hardware related issue).

**Comment by Erriez** [comment]
This temperature sensor is designed to run on low-end 8-bit microcontrollers with a CPU clock of 8MHz and lower. I tried GPIO interrupts, but it is impossible to measure accurate pulse width lengths withing a few us accuracy. Additionally, Arduino uses C++ which is heavy on such low-end devices. Changing a single line of code affects timing.

Interrupt handling in the middle of the sensor read results in a read failure. Disabling global interrupts as a blocking call is the only solution for this sensor type. An alternative is to use an I2C sensor with less critical timing.

Notice that the read calls are protected with a timeout, so a system hangup will never occur.

Conclusion: Impossible to fix and I'll close this ticket.
