### ISSUE TITLE
Add description of AM2302 (next to or instead of AM2303)

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezDHT22#9]
Not sure why, but most sensors note that they are a AM2302. Don't think there is a difference, probably a mis-stamp some time ago by a Chinese manufacturer which is now causing this confusion. So I would just add this typenumber to your readme for now:

> DHT22 - AM2303 temperature and humidity sensor library for Arduino

Can be changed into:

> DHT22 - AM2302 (AM2303) temperature and humidity sensor library for Arduino

Not sure if it's required to change in code or on wiki's, that's up to you off course.

**Comment by Erriez** [comment]
Thanks for your feedback. Fixed in commit 89de82b.

**Comment by baskapteijn** [comment]
Perfect :+1:
